package Modelo.ClasesFramework;
// Generated 17-mar-2017 18:55:03 by Hibernate Tools 4.3.1



/**
 * Proveedores generated by hbm2java
 */
public class Proveedores  implements java.io.Serializable {


     private String nit;
     private String nombre;
     private Integer telefono;
     private String direccion;

    public Proveedores() {
    }

	
    public Proveedores(String nit) {
        this.nit = nit;
    }
    public Proveedores(String nit, String nombre, Integer telefono, String direccion) {
       this.nit = nit;
       this.nombre = nombre;
       this.telefono = telefono;
       this.direccion = direccion;
    }
   
    public String getNit() {
        return this.nit;
    }
    
    public void setNit(String nit) {
        this.nit = nit;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(Integer telefono) {
        this.telefono = telefono;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }




}


